# Generated by Django 4.2.1 on 2023-05-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='point',
        ),
    ]
