# Generated by Django 4.2.1 on 2023-05-28 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_canditesapplied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanditesApplied',
            new_name='CandidateApplied',
        ),
    ]
