# Generated by Django 4.2.1 on 2023-06-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_canditesapplied_candidateapplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='positon',
            new_name='position',
        ),
    ]
